"""empty message

Revision ID: cb4c27a0bc65
Revises: e628f3aa8291
Create Date: 2018-10-15 18:51:56.961869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4c27a0bc65'
down_revision = 'e628f3aa8291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_number')
    # ### end Alembic commands ###
