"""empty message

Revision ID: 03f4dea9f8b6
Revises: 55e0e12c4ef7
Create Date: 2018-10-15 17:17:48.999620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f4dea9f8b6'
down_revision = '55e0e12c4ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'answer_number')
    # ### end Alembic commands ###
